---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kubernetes/external-secrets
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: devops-boilerplates-source
  targetNamespace: external-secrets
  timeout: 3m0s
  wait: true
