apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app
  namespace: flux-system
spec:
  releaseName: my-app
  interval: 5m
  chart:
    spec:
      chart: ./my-app
      sourceRef:
        kind: GitRepository
        name: devops-boilerplates-source
  values:
    replicaCount: 2
    image:
      repository: nginx
      tag: "1.25.0"
