---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: todoapp
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kubernetes/todoapp
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: devops-boilerplates-source
  targetNamespace: todoapp
  timeout: 3m0s
  wait: true
