apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/external-secrets
    repoURL: https://github.com/arodindev/devops-boilerplates
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true